version: "3.8"

services:
  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - "80:80"
    depends_on:
      - node
    networks:
      - api-network
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - api-network
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - api-network
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
